import type { Product } from "./types";
import { slugify } from "@/shared/lib/slug";

const c = (name: string) => slugify(name);

export const products: Product[] = [
  {
    id: "p-1",
    slug: "xenon-pro-14",
    title: "Xenon Pro 14",
    price: 59990,
    rating: 4.8,
    reviewsCount: 132,
    image: "/images/products/xenon-pro-14.jpg",
    categorySlug: c("Ноутбуки, планшеты и ПК"),
    badge: "Хит",
    stock: "in_stock",
  },
  {
    id: "p-2",
    slug: "vivid-air-2",
    title: "Vivid Air 2",
    price: 29990,
    rating: 4.6,
    reviewsCount: 98,
    image: "/images/products/vivid-air-2.jpg",
    categorySlug: c("Смартфоны и телефоны"),
    badge: "Новинка",
    stock: "limited",
  },
  {
    id: "p-3",
    slug: "auralink-mini",
    title: "Auralink Mini",
    price: 12490,
    rating: 4.7,
    reviewsCount: 76,
    image: "/images/products/auralink-mini.jpg",
    categorySlug: c("Аудио, фото и видео"),
    badge: "Хит",
    stock: "in_stock",
  },
  {
    id: "p-4",
    slug: "nexa-home-hub",
    title: "Nexa Home Hub",
    price: 18990,
    rating: 4.5,
    reviewsCount: 41,
    image: "/images/products/nexa-home-hub.jpg",
    categorySlug: c("Техника для дома"),
    badge: "Акция",
    stock: "in_stock",
  },
  {
    id: "p-5",
    slug: "pulse-neo",
    title: "Pulse Neo",
    price: 9990,
    rating: 4.4,
    reviewsCount: 52,
    image: "/images/products/pulse-neo.jpg",
    categorySlug: c("Смарт-часы и гаджеты"),
    badge: "Новинка",
    stock: "in_stock",
  },
  {
    id: "p-6",
    slug: "glow-kitchen",
    title: "Glow Kitchen",
    price: 7890,
    rating: 4.2,
    reviewsCount: 29,
    image: "/images/products/glow-kitchen.jpg",
    categorySlug: c("Техника для кухни"),
    badge: "Акция",
    stock: "limited",
  },
  {
    id: "p-7",
    slug: "voltstation-max",
    title: "VoltStation Max",
    price: 21990,
    rating: 4.3,
    reviewsCount: 64,
    image: "/images/products/voltstation-max.jpg",
    categorySlug: c("Энергообеспечение"),
    badge: "Хит",
    stock: "in_stock",
  },
  {
    id: "p-8",
    slug: "arena-play",
    title: "Arena Play",
    price: 44990,
    rating: 4.9,
    reviewsCount: 210,
    image: "/images/products/arena-play.jpg",
    categorySlug: c("Игровые консоли и гейминг"),
    badge: "Новинка",
    stock: "in_stock",
  },
  {
    id: "p-9",
    slug: "aurora-cam",
    title: "Aurora Cam",
    price: 15990,
    rating: 4.1,
    reviewsCount: 22,
    image: "/images/products/aurora-cam.jpg",
    categorySlug: c("Телевизоры и мультимедиа"),
    stock: "limited",
  },
  {
    id: "p-10",
    slug: "pure-guard",
    title: "Pure Guard",
    price: 6290,
    rating: 4.0,
    reviewsCount: 18,
    image: "/images/products/pure-guard.jpg",
    categorySlug: c("Красота и здоровье"),
    stock: "in_stock",
  },
  {
    id: "p-11",
    slug: "micro-wash",
    title: "Micro Wash",
    price: 3490,
    rating: 4.2,
    reviewsCount: 12,
    image: "/images/products/micro-wash.jpg",
    categorySlug: c("Бытовая химия"),
    stock: "in_stock",
  },
  {
    id: "p-12",
    slug: "sunrise-textile",
    title: "Sunrise Textile",
    price: 4590,
    rating: 4.3,
    reviewsCount: 16,
    image: "/images/products/sunrise-textile.jpg",
    categorySlug: c("Текстиль и декор"),
    stock: "in_stock",
  },
];
